version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: sorokailya/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/app/staticfiles/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: sorokailya/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/staticfiles

  gateway:
    image: sorokailya/kittygram_gateway:latest
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend